### PR TITLE
Support SBT 1.0

### PR DESCRIPTION
**Pull request by alonsodomin**
Updates the S3Plugin to become an auto plugin, migrates the syntax to be compatible with SBT 1.0 and adds cross SBT compilation

### CODE REVIEW

**Comment by bantonsson** [comment]
Does anybody else want to review this @eed3si9n @cunei, or should I go ahead and merge it?

**Comment by cunei** [comment]
Hi @bantonsson; in theory @emersonloureiro should be the person responsible for this plugin. He accepted to manage the project in Sep, 2016, see: https://github.com/sbt/sbt-s3/issues/30
However, I have not seen any activity from him since then. @emersonloureiro: are you still interested in managing the sbt-s3 plugin, or would you rather we took it back?

**Comment by emersonloureiro** [comment]
Hey folks. Sorry I'm late on this. For whatever reason, I haven't got any notification about this PR, only after @cunei ping my alias here. I'll take a look at this PR later today - at work right now I'm afraid. Sorry for the delay, I'll also see why on earth I'm getting no notifications for this project.

**Comment by emersonloureiro** [comment]
Actually, didn't realize the PR is small enough. Reviewed now, looks good to me, approving and will merge.

**Comment by emersonloureiro** [comment]
FYI Version 0.10 is out now and on a new bintray repo. The docs are updated accordingly.

**Pull request merged**
