### PR TITLE
Handling host containing region

### LINKED ISSUE #21: 'bucket does not exist ' error, when host contains region
When the `host` contains region, sbt-s3 is broken and it results in
```
[error] (root/*:s3Upload) com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket;
```
The host may look like this when it contains region

Bucket: `my-bucket`
Region: `ap-southeast-2`
Host: `my-bucket.s3-ap-southeast-2.amazonaws.com`

For more details about valid `region/s endpoint location`, please check out
http://www.bucketexplorer.com/documentation/amazon-s3--amazon-s3-buckets-and-regions.html

I think the cause of this is because [`getBucket()`](https://github.com/sbt/sbt-s3/blob/master/src/main/scala/S3Plugin.scala#L160) method uses a hard-coded S3 URL that is ".s3.amazonaws.com" and this cannot be used for the host containing region.

### PR DESCRIPTION
**Pull request by Kevin-Lee**
This fixes #21.

I'll deploy it to my personal bintray repo and test it with my project and will let you know the result.
I think this fix is simple but good enough to fix the issue with region.

### CODE REVIEW

**Comment by Kevin-Lee** [comment]
OK, I've just tested my fix and it works well.
So now I can have host like
```
my-bucket.s3-ap-southeast-2.amazonaws.com
```
which tells that the bucket is `my-bucket` and the region is `ap-southeast-2`.

Setting the region can avoid unnecessary process and redirection each time access S3.

**Comment by Kevin-Lee** [comment]
If anyone wants to test it, you can do so by simply putting the following repo and plugin in the `plugins.sbt`

```
resolvers += Resolver.url("3rd Party sbt-plugin-releases",
  url("https://dl.bintray.com/kevinlee/sbt-plugins"))(
  Resolver.ivyStylePatterns)

addSbtPlugin("com.typesafe.sbt" % "sbt-s3" % "0.8.1")
```

Then you can use the host with region.
```
bucket.s3-region. amazonaws.com
```
I'll update README doc as well although I'm not sure if my fix will ever be accepted.

**Comment by Kevin-Lee** [comment]
Also, your `bintray-sbt` plugin is too old (`0.1.1`). I've tested it with bintray-sbt `0.3.0` and sbt 0.13.8 (bintray-sbt 0.3.0 requires sbt 0.13.6+). So please let me know if you want it too after you decide to accept this PR.

**Comment by cunei** [comment]
Closing in favor of #32

**Pull request closed without merging**
