### PR TITLE
SBT version bump (0.13.17, 1.1.2)

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
ping @emersonloureiro   👋

**Comment by emersonloureiro** [comment]
Sorry for the delay. It's been a holiday weekend over here. I'll take a
look at it later on today and merge. Thanks.


Emerson

**Comment by emersonloureiro** [comment]
Merged

**Comment by sullis** [comment]
Thanks @emersonloureiro  #gilttech

**Comment by emersonloureiro** [comment]
Ha, I knew that alias sounded familiar @sullis . Thanks for the PRs. Keep them coming! Hope things are well for you over there.

**Pull request merged**
